AllCops:
  TargetRubyVersion: 2.4
Style/Documentation:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Layout/LeadingCommentSpace:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
